version: '3.8'

services:
  booking_databases:
    container_name: booking_databases
    image: postgres:latest
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'booking-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
    ports:
      - "5434:5432"
    networks:
      example_net:
        aliases:
          - booking_postgres

  # jaeger:
  #   image: jaegertracing/all-in-one:1.39
  #   container_name: example_jaeger
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "9411:9411"
  #     - "16686:16686"
  #     - "14268:14268"
  #   networks:
  #     example_net:
  #       aliases:
  #         - example_jaeger

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: booking_prometheus
    ports:
      - 9091:9090
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    networks:
      example_net:
        aliases:
          - booking_prometheus

  grafana:
    image: grafana/grafana:9.3.6
    container_name: booking_grafana
    ports:
      - 3101:3000
    networks:
      example_net:
        aliases:
          - booking_grafana

volumes:
  prometheus:

networks:
  example_net: