version: '3.8'

services:
  user_databases:
    container_name: user_databases
    image: postgres:latest
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'user-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
    ports:
      - "5435:5432"
    networks:
      example_net:
        aliases:
          - user_postgres
  backend-user-service:
    build:
      context: .
    container_name: backend-user-service
    networks:
      example_net:
        aliases:
          - backend-user-service
    ports:
      - 8082:8082
    depends_on:
      - user_databases

networks:
  example_net: